import { useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { lsDesign, supabase } from "./lib/supabase";

type CatalogItem={id:string;name:string;description:string|null;price_label:string|null;available:boolean;visible:boolean;position:number};
const fallback:CatalogItem[]=[
{id:"sac",name:"Sac",description:"Création graphique personnalisée pour un sac.",price_label:"Sur devis",available:true,visible:true,position:1},
{id:"arcadius",name:"Affichage Arcadius — 2 semaines",description:"Campagne d'affichage personnalisée à l'Arcadius.",price_label:"Sur devis",available:true,visible:true,position:2},
{id:"carte-visite",name:"Carte de visite",description:"Création d'une carte de visite sur mesure.",price_label:"Sur devis",available:true,visible:true,position:3},
{id:"carte-fidelite",name:"Carte de fidélité",description:"Création d'une carte de fidélité personnalisée.",price_label:"Sur devis",available:true,visible:true,position:4},
];

export default function App(){
 const [session,setSession]=useState<Session|null>(null); const [items,setItems]=useState<CatalogItem[]>(fallback); const [view,setView]=useState<"catalogue"|"commandes"|"admin">("catalogue");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{lsDesign.from("catalog").select("id,name,description,price_label,available,visible,position").eq("visible",true).eq("archived",false).order("position").then(({data})=>{if(data?.length)setItems(data as CatalogItem[])})},[]);
 const name=useMemo(()=>session?.user.user_metadata?.full_name||session?.user.user_metadata?.name||session?.user.user_metadata?.preferred_username||"Mon espace",[session]);
 const login=()=>supabase.auth.signInWithOAuth({provider:"discord",options:{redirectTo:window.location.origin+import.meta.env.BASE_URL,scopes:"identify guilds.members.read"}});
 return <div className="app"><header><a className="brand" onClick={()=>setView("catalogue")}><b>LS</b><span>DESIGN<small>COMMANDES</small></span></a><nav><button className={view==="catalogue"?"active":""} onClick={()=>setView("catalogue")}>Catalogue</button><button className={view==="commandes"?"active":""} onClick={()=>setView("commandes")}>Mes commandes</button>{session&&<button className={view==="admin"?"active":""} onClick={()=>setView("admin")}>Gestion</button>}</nav>{session?<div className="account"><span>{name}</span><button onClick={()=>supabase.auth.signOut()}>Déconnexion</button></div>:<button className="discord" onClick={login}>Connexion Discord</button>}</header>
 <main>{view==="catalogue"&&<><section className="hero"><div><span className="kicker">CRÉATION • IMPRESSION • IDENTITÉ VISUELLE</span><h1>Donnez forme à<br/><em>vos idées.</em></h1><p>Choisissez votre support, décrivez votre projet et suivez votre commande directement depuis votre espace LS DESIGN.</p>{session?<button className="primary" onClick={()=>setView("commandes")}>Ouvrir mon espace →</button>:<button className="primary" onClick={login}>Commander avec Discord →</button>}</div><div className="orb"><span>LS</span></div></section><section className="catalog"><div className="section-title"><div><span>NOTRE CATALOGUE</span><h2>Que souhaitez-vous créer ?</h2></div><p>Chaque création est réalisée sur mesure.</p></div><div className="grid">{items.map((x,i)=><article key={x.id}><div className="num">0{i+1}</div><div className="icon">{x.name.slice(0,1)}</div><h3>{x.name}</h3><p>{x.description}</p><footer><b>{x.price_label||"Sur devis"}</b><button disabled={!x.available} onClick={session?()=>setView("commandes"):login}>{x.available?"Commander":"Indisponible"}</button></footer></article>)}</div></section></>}
 {view==="commandes"&&<section className="workspace"><span className="kicker">ESPACE CLIENT</span><h1>{session?"Mes commandes":"Connexion requise"}</h1><p>{session?"Le suivi des commandes et la messagerie arrivent ici. La base Supabase est prête à recevoir les premières commandes.":"Connectez-vous avec Discord pour créer et suivre vos commandes."}</p>{!session&&<button className="primary" onClick={login}>Connexion Discord</button>} {session&&<div className="empty">Aucune commande pour le moment.<button className="primary" onClick={()=>setView("catalogue")}>Créer une commande</button></div>}</section>}
 {view==="admin"&&<section className="workspace"><span className="kicker">GESTION LS DESIGN</span><h1>Administration</h1><p>Catalogue, commandes, staff, grades Discord et paramètres seront administrables depuis cet espace.</p><div className="admin-grid">{["Commandes","Catalogue","Staff & grades","Paramètres"].map(x=><div className="admin-card" key={x}><b>{x}</b><span>Module en préparation</span></div>)}</div></section>}</main><footer className="site-footer"><b>LS DESIGN</b><span>Panel nouvelle génération · Supabase + Discord</span></footer></div>;
}
