import { useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { lsDesign, supabase } from "./lib/supabase";

type CatalogItem={id:string;name:string;description:string|null;price_label:string|null;available:boolean;visible:boolean;position:number};
type Order={id:string;order_number:string;catalog_item_id:string|null;catalog_item_name:string;description:string;status:string;company_name:string|null;phone:string|null;created_at:string};
const fallback:CatalogItem[]=[
{id:"sac",name:"Sac",description:"Création graphique personnalisée pour un sac.",price_label:"Sur devis",available:true,visible:true,position:1},
{id:"arcadius",name:"Affichage Arcadius — 2 semaines",description:"Campagne d'affichage personnalisée à l'Arcadius.",price_label:"Sur devis",available:true,visible:true,position:2},
{id:"carte-visite",name:"Carte de visite",description:"Création d'une carte de visite sur mesure.",price_label:"Sur devis",available:true,visible:true,position:3},
{id:"carte-fidelite",name:"Carte de fidélité",description:"Création d'une carte de fidélité personnalisée.",price_label:"Sur devis",available:true,visible:true,position:4},
];
const statusLabel:Record<string,string>={nouvelle:"Nouvelle",en_cours:"En cours",attente_client:"En attente",terminee:"Terminée",annulee:"Annulée"};

export default function App(){
 const [session,setSession]=useState<Session|null>(null),[items,setItems]=useState<CatalogItem[]>(fallback),[orders,setOrders]=useState<Order[]>([]);
 const [view,setView]=useState<"catalogue"|"commandes">("catalogue"),[selected,setSelected]=useState<CatalogItem|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState("");
 const [form,setForm]=useState({description:"",company:"",phone:""});
 const name=useMemo(()=>session?.user.user_metadata?.full_name||session?.user.user_metadata?.name||session?.user.user_metadata?.preferred_username||"Mon espace",[session]);
 const login=()=>supabase.auth.signInWithOAuth({provider:"discord",options:{redirectTo:window.location.origin+import.meta.env.BASE_URL,scopes:"identify guilds.members.read"}});
 const loadOrders=async()=>{if(!session)return;const {data}=await lsDesign.from("orders").select("id,order_number,catalog_item_id,catalog_item_name,description,status,company_name,phone,created_at").order("created_at",{ascending:false});if(data)setOrders(data as Order[])};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{lsDesign.from("catalog").select("id,name,description,price_label,available,visible,position").eq("visible",true).eq("archived",false).order("position").then(({data})=>{if(data?.length)setItems(data as CatalogItem[])})},[]);
 useEffect(()=>{if(session){lsDesign.rpc("ensure_profile").then(()=>loadOrders())}else setOrders([])},[session]);
 const choose=(x:CatalogItem)=>{if(!session){void login();return}setSelected(x);setView("commandes");setNotice("")};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;setLoading(true);setNotice("");const {data,error}=await lsDesign.rpc("create_order",{p_catalog_item_id:selected.id,p_description:form.description,p_company_name:form.company||null,p_phone:form.phone||null});setLoading(false);if(error){setNotice("Impossible de créer la commande pour le moment.");return}setNotice(`Commande ${(data as Order).order_number} créée avec succès.`);setForm({description:"",company:"",phone:""});setSelected(null);await loadOrders()};
 return <div className="app"><header><a className="brand" onClick={()=>setView("catalogue")}><b>LS</b><span>DESIGN<small>COMMANDES</small></span></a><nav><button className={view==="catalogue"?"active":""} onClick={()=>setView("catalogue")}>Catalogue</button><button className={view==="commandes"?"active":""} onClick={()=>setView("commandes")}>Mes commandes</button></nav>{session?<div className="account"><span>{name}</span><button onClick={()=>supabase.auth.signOut()}>Déconnexion</button></div>:<button className="discord" onClick={login}>Connexion Discord</button>}</header>
 <main>{view==="catalogue"&&<><section className="hero"><div><span className="kicker">CRÉATION • IMPRESSION • IDENTITÉ VISUELLE</span><h1>Donnez forme à<br/><em>vos idées.</em></h1><p>Choisissez votre support, décrivez votre projet et suivez votre commande directement depuis votre espace LS DESIGN.</p><button className="primary" onClick={session?()=>setView("commandes"):login}>{session?"Ouvrir mon espace →":"Commander avec Discord →"}</button></div><div className="orb"><span>LS</span></div></section><section className="catalog"><div className="section-title"><div><span>NOTRE CATALOGUE</span><h2>Que souhaitez-vous créer ?</h2></div><p>Chaque création est réalisée sur mesure.</p></div><div className="grid">{items.map((x,i)=><article key={x.id}><div className="num">0{i+1}</div><div className="icon">{x.name.slice(0,1)}</div><h3>{x.name}</h3><p>{x.description}</p><footer><b>{x.price_label||"Sur devis"}</b><button disabled={!x.available} onClick={()=>choose(x)}>{x.available?"Commander":"Indisponible"}</button></footer></article>)}</div></section></>}
 {view==="commandes"&&<section className="workspace"><span className="kicker">ESPACE CLIENT</span><h1>{session?"Mes commandes":"Connexion requise"}</h1>{!session?<><p>Connectez-vous avec Discord pour créer et suivre vos commandes.</p><button className="primary" onClick={login}>Connexion Discord</button></>:<><div className="workspace-head"><p>Bonjour {name}. Retrouvez ici vos demandes et leur avancement.</p><button className="primary" onClick={()=>setView("catalogue")}>+ Nouvelle commande</button></div>{notice&&<div className="notice">{notice}</div>}{selected&&<form className="order-form" onSubmit={submit}><div className="form-title"><div><span>NOUVELLE COMMANDE</span><h2>{selected.name}</h2></div><button type="button" className="close" onClick={()=>setSelected(null)}>×</button></div><label>Décrivez votre projet<textarea required minLength={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Format, texte, couleurs, quantité, délai souhaité…"/></label><div className="form-row"><label>Entreprise / Faction<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})} placeholder="Optionnel"/></label><label>Téléphone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Optionnel"/></label></div><button className="primary" disabled={loading}>{loading?"Création…":"Envoyer la commande →"}</button></form>}<div className="orders">{orders.length===0&&!selected?<div className="empty">Vous n'avez encore aucune commande.<button className="primary" onClick={()=>setView("catalogue")}>Voir le catalogue</button></div>:orders.map(o=><article className="order" key={o.id}><div><span className="order-no">{o.order_number}</span><h3>{o.catalog_item_name}</h3><p>{o.description}</p></div><div className="order-meta"><span className={"badge "+o.status}>{statusLabel[o.status]||o.status}</span><small>{new Date(o.created_at).toLocaleDateString("fr-FR")}</small></div></article>)}</div></>}</section>}</main><footer className="site-footer"><b>LS DESIGN</b><span>Panel nouvelle génération · Supabase + Discord</span></footer></div>;
}
