-- LS DESIGN initial schema
-- Intentionally isolated from existing EMS tables using the ls_design schema.

create schema if not exists ls_design;

revoke all on schema ls_design from public, anon, authenticated;
grant usage on schema ls_design to service_role;

create table if not exists ls_design.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  discord_user_id text not null unique,
  guild_nickname text,
  avatar_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ls_design.role_mappings (
  discord_role_id text primary key,
  grade text not null,
  label text not null,
  priority integer not null default 0,
  permissions jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ls_design.catalog (
  id text primary key,
  name text not null,
  description text not null default '',
  price_label text not null default 'Sur devis',
  image_url text,
  available boolean not null default true,
  visible boolean not null default true,
  position integer not null default 0,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ls_design.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_profile_id uuid references ls_design.profiles(id) on delete set null,
  assigned_staff_id uuid references ls_design.profiles(id) on delete set null,
  catalog_item_id text references ls_design.catalog(id) on delete set null,
  catalog_item_name text not null,
  description text not null default '',
  status text not null default 'nouvelle',
  company_name text,
  phone text,
  discord_thread_id text,
  discord_message_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ls_design.messages (
  id bigint generated by default as identity primary key,
  order_id uuid not null references ls_design.orders(id) on delete cascade,
  author_profile_id uuid references ls_design.profiles(id) on delete set null,
  author_type text not null check (author_type in ('client','staff','system')),
  author_name text not null,
  body text not null check (char_length(trim(body)) between 1 and 6000),
  attachments jsonb not null default '[]'::jsonb,
  reply_to_message_id bigint references ls_design.messages(id) on delete set null,
  origin text not null default 'panel',
  discord_message_id text,
  created_at timestamptz not null default now()
);

create table if not exists ls_design.audit_log (
  id bigint generated by default as identity primary key,
  order_id uuid references ls_design.orders(id) on delete set null,
  actor_profile_id uuid references ls_design.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists ls_design.app_settings (
  key text primary key,
  value jsonb not null default 'null'::jsonb,
  description text not null default '',
  updated_at timestamptz not null default now()
);

alter table ls_design.profiles enable row level security;
alter table ls_design.role_mappings enable row level security;
alter table ls_design.catalog enable row level security;
alter table ls_design.orders enable row level security;
alter table ls_design.messages enable row level security;
alter table ls_design.audit_log enable row level security;
alter table ls_design.app_settings enable row level security;

grant usage on schema ls_design to authenticated;
grant select on ls_design.catalog to authenticated;
grant select on ls_design.profiles to authenticated;
grant select on ls_design.role_mappings to authenticated;
grant select, insert, update on ls_design.orders to authenticated;
grant select, insert on ls_design.messages to authenticated;
grant select on ls_design.audit_log to authenticated;
grant select on ls_design.app_settings to authenticated;

create policy "profile_self_read"
on ls_design.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "catalog_authenticated_read"
on ls_design.catalog for select
to authenticated
using (visible = true and archived = false);

create policy "order_customer_read"
on ls_design.orders for select
to authenticated
using (customer_profile_id = (select auth.uid()) or assigned_staff_id = (select auth.uid()));

create policy "order_customer_insert"
on ls_design.orders for insert
to authenticated
with check (customer_profile_id = (select auth.uid()));

create policy "order_assigned_staff_update"
on ls_design.orders for update
to authenticated
using (assigned_staff_id = (select auth.uid()))
with check (assigned_staff_id = (select auth.uid()));

create policy "messages_order_participant_read"
on ls_design.messages for select
to authenticated
using (
  exists (
    select 1
    from ls_design.orders o
    where o.id = messages.order_id
      and (o.customer_profile_id = (select auth.uid()) or o.assigned_staff_id = (select auth.uid()))
  )
);

create policy "messages_order_participant_insert"
on ls_design.messages for insert
to authenticated
with check (
  author_profile_id = (select auth.uid())
  and exists (
    select 1
    from ls_design.orders o
    where o.id = messages.order_id
      and (o.customer_profile_id = (select auth.uid()) or o.assigned_staff_id = (select auth.uid()))
  )
);

insert into ls_design.app_settings(key, value, description)
values
  ('site_active', 'true'::jsonb, 'Active ou désactive le site client'),
  ('orders_active', 'true'::jsonb, 'Autorise ou bloque les nouvelles commandes'),
  ('maintenance_message', '"Le site est temporairement indisponible."'::jsonb, 'Message affiché pendant une maintenance')
on conflict (key) do nothing;

insert into ls_design.catalog(id, name, description, price_label, available, visible, position)
values
  ('sac', 'Sac', 'Création graphique personnalisée pour un sac.', 'Sur devis', true, true, 1),
  ('arcadius', 'Affichage Arcadius — 2 semaines', 'Création graphique pour une campagne publicitaire Arcadius.', 'Sur devis', true, true, 2),
  ('carte-visite', 'Carte de visite', '', 'Sur devis', true, true, 3),
  ('carte-fidelite', 'Carte de fidélité', '', 'Sur devis', true, true, 4),
  ('flocage-vehicule', 'Flocage véhicule', '', 'Sur devis', false, true, 5),
  ('tag-bombe', 'Tag bombe', '', 'Sur devis', false, true, 6)
on conflict (id) do nothing;
